# Talia Platform UI - Independent Deployment Config v0.1.0 (Alpha)
# Repository: https://github.com/zomarc/talia-platform

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
